name = "TwMakieHelpers"
uuid = "319ff0f0-2ac7-4e2b-af60-1edd76e04ccb"
authors = ["Thomas Wutzler <twutz@bgc-jena.mpg.de> and contributors"]
version = "1.0.0-DEV"

[deps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[weakdeps]
AbstractMCMC = "80f14c24-f653-4e6a-9b94-39d6b0f70001"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[extensions]
TwMakieHelpersAbstractMCMCExt = "AbstractMCMC"
TwMakieHelpersDistributionsExt = "Distributions"

[compat]
Makie = "0.21, 0.22"
julia = "1.10"
AbstractMCMC = "5.3"
Distributions = "0.25"

[workspace]
projects = ["test", "docs"]
