name: CompatHelper
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/compathelper-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh: ${{ secrets.DOCUMENTER_KEY }}
  keepalive-job:
      name: Keepalive Workflow
      runs-on: ubuntu-latest
      permissions:
        actions: write
      steps:
        - uses: actions/checkout@v4
          with:
            ref: 'keepalive'      # The branch, tag or SHA to checkout.       
        - uses: gautamkrishnar/keepalive-workflow@v2          
